import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import type { Invoice, LineItem } from '../types/invoice';
import { formatCurrency, formatDate } from '../types/invoice';

// Add types to jsPDF for autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export const generatePDF = (invoice: Invoice): string => {
  const doc = new jsPDF();
  
  // Set document properties
  doc.setProperties({
    title: `Invoice-${invoice.invoiceNumber}`,
    author: invoice.senderName,
    subject: `Invoice for ${invoice.clientName}`,
    keywords: 'invoice, bill',
    creator: 'InvoiceFlow'
  });
  
  // Add fonts and styling
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  // Start with sender information
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246); // Primary color
  doc.text(invoice.senderName, 14, 22);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  
  // Sender details
  const senderAddressLines = invoice.senderAddress.split('\n');
  let y = 30;
  
  senderAddressLines.forEach(line => {
    doc.text(line, 14, y);
    y += 5;
  });
  
  doc.text(invoice.senderEmail, 14, y);
  y += 5;
  doc.text(invoice.senderPhone, 14, y);
  
  // Add INVOICE text
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246); // Primary color
  doc.text('INVOICE', 140, 22, { align: 'right' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  
  // Invoice details on right
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 140, 32, { align: 'right' });
  doc.text(`Date: ${formatDate(invoice.issueDate)}`, 140, 37, { align: 'right' });
  doc.text(`Due Date: ${formatDate(invoice.dueDate)}`, 140, 42, { align: 'right' });
  
  // Add line
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 55, 196, 55);
  
  // Client information
  doc.setFontSize(12);
  doc.text('Bill To:', 14, 65);
  
  doc.setFontSize(11);
  doc.text(invoice.clientName, 14, 72);
  
  doc.setFontSize(10);
  const clientAddressLines = invoice.clientAddress.split('\n');
  y = 79;
  
  clientAddressLines.forEach(line => {
    doc.text(line, 14, y);
    y += 5;
  });
  
  doc.text(invoice.clientEmail, 14, y);
  
  // Line items table
  const tableColumn = ['Description', 'Quantity', 'Rate', 'Amount'];
  const tableRows: string[][] = [];
  
  invoice.items.forEach((item: LineItem) => {
    const formattedRow = [
      item.description,
      item.quantity.toString(),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.amount, invoice.currency),
    ];
    tableRows.push(formattedRow);
  });
  
  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 100,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { 
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { cellWidth: 30, halign: 'center' },
      2: { cellWidth: 30, halign: 'right' },
      3: { cellWidth: 30, halign: 'right' },
    },
    didDrawPage: (data) => {
      // Footer on each page
      doc.setFontSize(8);
      doc.text(
        'Invoice generated by InvoiceFlow',
        data.settings.margin.left,
        doc.internal.pageSize.height - 10
      );
    }
  });
  
  // Calculate the Y position after the table
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  // Add summary info
  doc.text(`Subtotal:`, 140, finalY, { align: 'right' });
  doc.text(formatCurrency(invoice.subtotal, invoice.currency), 190, finalY, { align: 'right' });
  
  doc.text(`Tax (${invoice.taxRate}%):`, 140, finalY + 5, { align: 'right' });
  doc.text(formatCurrency(invoice.taxAmount, invoice.currency), 190, finalY + 5, { align: 'right' });
  
  // Add total
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total:`, 140, finalY + 12, { align: 'right' });
  doc.setTextColor(59, 130, 246); // Primary color
  doc.text(formatCurrency(invoice.total, invoice.currency), 190, finalY + 12, { align: 'right' });
  
  // Reset font
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  // Add notes
  if (invoice.notes) {
    doc.setFontSize(11);
    doc.text('Notes:', 14, finalY + 25);
    doc.setFontSize(10);
    doc.text(invoice.notes, 14, finalY + 32);
  }
  
  // Return the PDF as a data URL
  return doc.output('datauristring');
};

export const downloadPDF = (invoice: Invoice) => {
  const doc = new jsPDF();
  
  // Same code as above for generating PDF content
  // Set document properties
  doc.setProperties({
    title: `Invoice-${invoice.invoiceNumber}`,
    author: invoice.senderName,
    subject: `Invoice for ${invoice.clientName}`,
    keywords: 'invoice, bill',
    creator: 'InvoiceFlow'
  });
  
  // Add fonts and styling
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  // Start with sender information
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246); // Primary color
  doc.text(invoice.senderName, 14, 22);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  
  // Sender details
  const senderAddressLines = invoice.senderAddress.split('\n');
  let y = 30;
  
  senderAddressLines.forEach(line => {
    doc.text(line, 14, y);
    y += 5;
  });
  
  doc.text(invoice.senderEmail, 14, y);
  y += 5;
  doc.text(invoice.senderPhone, 14, y);
  
  // Add INVOICE text
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246); // Primary color
  doc.text('INVOICE', 140, 22, { align: 'right' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  
  // Invoice details on right
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 140, 32, { align: 'right' });
  doc.text(`Date: ${formatDate(invoice.issueDate)}`, 140, 37, { align: 'right' });
  doc.text(`Due Date: ${formatDate(invoice.dueDate)}`, 140, 42, { align: 'right' });
  
  // Add line
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 55, 196, 55);
  
  // Client information
  doc.setFontSize(12);
  doc.text('Bill To:', 14, 65);
  
  doc.setFontSize(11);
  doc.text(invoice.clientName, 14, 72);
  
  doc.setFontSize(10);
  const clientAddressLines = invoice.clientAddress.split('\n');
  y = 79;
  
  clientAddressLines.forEach(line => {
    doc.text(line, 14, y);
    y += 5;
  });
  
  doc.text(invoice.clientEmail, 14, y);
  
  // Line items table
  const tableColumn = ['Description', 'Quantity', 'Rate', 'Amount'];
  const tableRows: string[][] = [];
  
  invoice.items.forEach((item: LineItem) => {
    const formattedRow = [
      item.description,
      item.quantity.toString(),
      formatCurrency(item.rate, invoice.currency),
      formatCurrency(item.amount, invoice.currency),
    ];
    tableRows.push(formattedRow);
  });
  
  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 100,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { 
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { cellWidth: 30, halign: 'center' },
      2: { cellWidth: 30, halign: 'right' },
      3: { cellWidth: 30, halign: 'right' },
    },
    didDrawPage: (data) => {
      // Footer on each page
      doc.setFontSize(8);
      doc.text(
        'Invoice generated by InvoiceFlow',
        data.settings.margin.left,
        doc.internal.pageSize.height - 10
      );
    }
  });
  
  // Calculate the Y position after the table
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  // Add summary info
  doc.text(`Subtotal:`, 140, finalY, { align: 'right' });
  doc.text(formatCurrency(invoice.subtotal, invoice.currency), 190, finalY, { align: 'right' });
  
  doc.text(`Tax (${invoice.taxRate}%):`, 140, finalY + 5, { align: 'right' });
  doc.text(formatCurrency(invoice.taxAmount, invoice.currency), 190, finalY + 5, { align: 'right' });
  
  // Add total
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total:`, 140, finalY + 12, { align: 'right' });
  doc.setTextColor(59, 130, 246); // Primary color
  doc.text(formatCurrency(invoice.total, invoice.currency), 190, finalY + 12, { align: 'right' });
  
  // Reset font
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  // Add notes
  if (invoice.notes) {
    doc.setFontSize(11);
    doc.text('Notes:', 14, finalY + 25);
    doc.setFontSize(10);
    doc.text(invoice.notes, 14, finalY + 32);
  }
  
  // Generate file name
  const fileName = `Invoice-${invoice.invoiceNumber}-${invoice.clientName.replace(/\s+/g, '-')}.pdf`;
  
  // Download the PDF
  doc.save(fileName);
};
